/**
 * AI-Assistant Brain — the single seam where the assistant produces a reply.
 *
 * The internal AI-assistant chat is a plain chat surface: no keyword commands,
 * no protocol registry, no Telegram coupling. The reply is generated by a local
 * LLM served over Ollama ({@link module:ollamaClient}), which may call registered
 * tools (see {@link module:toolRegistry}) to reach real application data before
 * answering. Everything upstream (the Kafka consumer, message persistence,
 * WebSocket delivery, receipts) is unaffected — this is the ONLY place model
 * logic lives.
 *
 * When {@link AI_ASSISTANT}.ENABLED is false (no model configured) this returns a
 * fixed placeholder so the feature degrades cleanly. When the model is enabled
 * but the call fails, the error propagates: the responder counts it as a failed
 * answer and the Kafka consumer retries it. Tool-execution errors are the
 * exception: they are reported back to the model as a tool result so it can
 * explain, rather than failing the whole turn.
 *
 * Do not re-introduce keyword commands, protocols, or Telegram references here —
 * this surface is AI-assistant only.
 *
 * @module assistantBrain
 */

import type {serverLogger} from "@coreModule/loggers/serverLog";
import {AI_ASSISTANT, ANTHROPIC} from "@coreModule/environment";
import {OllamaChatMessage, OllamaTool, OllamaToolCall} from "@coreModule/domain/ai/ollamaClient";
import {assistantChat} from "@coreModule/domain/ai/assistantModelClient";
import {getAssistantTool, getAssistantTools} from "@coreModule/domain/ai/tools/toolRegistry";
import type {
    AssistantReplyAudience,
    AssistantTool,
    AssistantToolContext,
} from "@coreModule/domain/ai/tools/assistantTool.types";

/**
 * One prior turn in the AI-channel conversation, already decrypted and reduced to
 * the two roles the model cares about. The bot's own past replies map to
 * `assistant`; the human's past messages map to `user`.
 */
export interface AssistantConversationTurn {
    role: "user" | "assistant";
    content: string;
}

/**
 * Everything the LLM needs to compose a contextual reply. Kept as a single object
 * so extending it later is a drop-in change with no callsite churn — add fields
 * (company profile, etc.) as the model needs them.
 */
export interface AssistantReplyContext {
    /** The user's message text (decrypted, raw). */
    text: string;
    /**
     * Prior turns of this conversation, oldest-first, excluding the current
     * message. Gives the model the context to resolve follow-ups ("the cheaper
     * ones", "show me more"). Omitted/empty for the first message in a thread.
     */
    history?: AssistantConversationTurn[];
    /** The AI channel the conversation belongs to. */
    channelId: string;
    /** The company scope of the conversation. */
    companyId: string;
    /** The human user the assistant is answering. */
    userId: string;
    /** Best available display name for the human, for a personalised reply. */
    userDisplayName?: string;
    /** Language the reply should be produced in, when available. */
    languageCode?: string;
    /**
     * Who the assistant is answering. Defaults to `internal`; the public-website
     * visitor chat passes `public`, which both narrows the tool set and swaps in
     * the outward-facing persona.
     */
    audience?: AssistantReplyAudience;
    /** Tenant name, so a public-facing reply can speak as the company. */
    companyName?: string;
    /** Tenant-configured persona appended to the public system prompt. */
    companyPersona?: string;
}

/**
 * Reply used when the assistant is switched off (`AI_ASSISTANT_ENABLED` is not
 * `true`). Configurable via `AI_ASSISTANT_OFFLINE_MESSAGE` so a maintenance
 * window can say something the public is happy to read, and so it matches the
 * responder-unreachable notice word for word.
 */
const offlineReply = () => AI_ASSISTANT.OFFLINE_MESSAGE;

/** Default system prompt when AI_ASSISTANT_SYSTEM_PROMPT is not set. */
const DEFAULT_SYSTEM_PROMPT =
    "You are the AI assistant embedded in Arpeggio, a property-management platform. " +
    "Answer the user's questions helpfully, accurately, and concisely. If you are not " +
    "sure about something, say so rather than inventing details. When a tool can answer " +
    "the question with real data, call it and base your answer strictly on its result — " +
    "never fabricate records the tool did not return.";

/**
 * Safety cap on tool-calling rounds per reply. Each round is one model call plus
 * the tools it requested. Bounded so a model that loops on tool calls can't spin
 * forever; on exhaustion we ask once more without tools to force a text answer.
 */
const MAX_TOOL_ITERATIONS = 5;

/** Cap on a single tool result fed back to the model, to protect the context window. */
const MAX_TOOL_RESULT_CHARS = 8000;

/** Returned when the model produces no text (e.g. only whitespace). */
const EMPTY_REPLY_FALLBACK =
    "Sorry, I couldn't produce an answer for that. Could you rephrase or add a little more detail?";

/**
 * Base prompt for the public website chat.
 *
 * NOTE: this prompt is manners, not security. What an anonymous visitor can
 * reach is decided by the tool audience filter in the registry — internal tools
 * are never offered to the model in a public conversation, so no amount of
 * prompt injection can call them. Keep the wording here about tone and
 * helpfulness, and never rely on it to withhold data.
 */
const PUBLIC_SYSTEM_PROMPT =
    "You are the assistant on a real-estate company's public website, talking to a " +
    "prospective buyer or tenant who is browsing anonymously. Be warm, brief, and " +
    "concrete. Use the available tools to answer questions about available properties, " +
    "projects, and buildings, and base every factual claim strictly on what a tool " +
    "returned — never invent listings, prices, or availability. You have no access to " +
    "information about other customers, and you must never discuss internal business " +
    "details such as costs, commissions, or other clients. If you cannot answer from " +
    "the tools, or the visitor asks for something that needs a person, say so plainly " +
    "and offer to connect them with the team.";

/**
 * Build the system prompt, layering the configured/default base prompt with the
 * per-conversation context the model should be aware of (who it's talking to and
 * which language to reply in).
 */
function buildSystemPrompt(context: AssistantReplyContext): string {
    const isPublic = context.audience === "public";
    const base = isPublic
        ? PUBLIC_SYSTEM_PROMPT
        : (AI_ASSISTANT.SYSTEM_PROMPT.trim() || DEFAULT_SYSTEM_PROMPT);
    const parts = [base];

    if (isPublic && context.companyName) {
        parts.push(`You represent ${context.companyName}.`);
    }
    if (isPublic && context.companyPersona?.trim()) {
        parts.push(context.companyPersona.trim());
    }
    if (context.userDisplayName) {
        parts.push(`You are speaking with ${context.userDisplayName}.`);
    }
    if (context.languageCode) {
        parts.push(`Reply in the user's language (locale: ${context.languageCode}).`);
    }

    // Ground the model in the current date so it can resolve relative dates
    // ("today", "this Friday", "next month") into the absolute ISO dates the
    // data tools expect, and steer it toward valid tool arguments — both are
    // common failure modes for small local models when calling tools.
    const now = new Date();
    const isoDate = now.toISOString().slice(0, 10);
    const weekday = now.toLocaleDateString("en-US", {weekday: "long", timeZone: "UTC"});
    parts.push(
        `Today's date is ${isoDate} (${weekday}, UTC). When a tool takes a date, ` +
            `resolve any relative date yourself to an absolute YYYY-MM-DD value first.`
    );
    parts.push(
        "When a tool parameter is an enum, pass exactly one of its allowed values " +
            "verbatim — do not invent, translate, or pluralize them. Only pass tool " +
            "arguments the user actually asked for; do not add filters they did not request."
    );

    return parts.join(" ");
}

/** Map a registered tool to the OpenAI-style function schema Ollama expects. */
function toOllamaTool(tool: AssistantTool): OllamaTool {
    return {
        type: "function",
        function: {
            name: tool.name,
            description: tool.description,
            parameters: tool.parameters
        }
    };
}

/**
 * Normalize raw tool arguments from the model before dispatch: drop keys whose
 * value is "unset" — `null`, `undefined`, or an empty/whitespace-only string.
 * Small local models routinely emit these for the optional parameters they aren't
 * using (e.g. `{search: "", status: null}`), which would otherwise fail a tool's
 * `.optional()` (undefined-only) or `.min(1)` string Zod schema. Non-object args
 * pass through as `{}`.
 */
function normalizeToolArgs(args: unknown): unknown {
    if (args == null || typeof args !== "object" || Array.isArray(args)) {
        return args ?? {};
    }
    const out: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(args as Record<string, unknown>)) {
        if (value === null || value === undefined) {
            continue;
        }
        if (typeof value === "string" && value.trim() === "") {
            continue;
        }
        out[key] = value;
    }
    return out;
}

/** JSON-stringify a tool result, truncating to protect the model's context window. */
function serializeToolResult(result: unknown): string {
    let text: string;
    try {
        text = JSON.stringify(result ?? null);
    } catch {
        text = String(result);
    }
    if (text.length > MAX_TOOL_RESULT_CHARS) {
        text = text.slice(0, MAX_TOOL_RESULT_CHARS) + "…(truncated)";
    }
    return text;
}

/**
 * Dispatch one tool call to its registered handler and return the result text to
 * feed back to the model. Unknown tools and thrown errors are returned as a JSON
 * `{error}` payload (not thrown) so the model can explain the failure instead of
 * the whole turn dying. `arguments` is untrusted model output — the tool itself
 * re-validates and scopes it.
 */
async function dispatchToolCall(
    call: OllamaToolCall,
    ctx: AssistantToolContext,
    logger?: serverLogger
): Promise<string> {
    const name = call.function?.name;
    // Resolved through the audience filter: a model that names a tool it was
    // never offered (hallucination or injection) gets "unknown tool", not the
    // tool. This is defence in depth behind the offered-tool list.
    const tool = name ? getAssistantTool(name, ctx.audience) : undefined;

    if (!tool) {
        logger?.warn?.(
            `Assistant requested unknown or out-of-audience tool "${name}" (audience: ${ctx.audience})`
        );
        return serializeToolResult({error: `Unknown tool: ${name ?? "(unnamed)"}`});
    }

    try {
        const result = await tool.execute(normalizeToolArgs(call.function.arguments), ctx);
        logger?.debug?.(`Tool ${name} executed for company ${ctx.companyId}`);
        return serializeToolResult(result);
    } catch (err: any) {
        logger?.warn?.(`Tool ${name} failed: ${err?.message ?? err}`);
        return serializeToolResult({error: `Tool ${name} failed: ${err?.message ?? "unknown error"}`});
    }
}

/**
 * Produce the assistant's reply to a user message using the local LLM, running a
 * bounded tool-calling loop so the model can fetch real data before answering.
 *
 * When the assistant is disabled (no model configured) this returns a fixed
 * placeholder. Otherwise it prompts the local model via Ollama; if the model asks
 * to call tools, each is dispatched (scoped to the human's company) and its
 * result is fed back, repeating up to {@link MAX_TOOL_ITERATIONS} times until the
 * model returns a text answer.
 *
 * A thrown error from the model call itself (unreachable/timeout/no message) is
 * intentionally NOT swallowed: the responder counts it as a failed answer and the
 * Kafka consumer retries it, so transient model outages recover on their own.
 * Tool-execution errors, by contrast, are handed back to the model as tool
 * results so it can explain them.
 *
 * @param context - Message text plus identifiers/context for the reply.
 * @param logger - Optional logger for tracing.
 * @returns The reply text to deliver back into the internal chat.
 */
export async function generateAssistantReply(
    context: AssistantReplyContext,
    logger?: serverLogger
): Promise<string> {
    if (!AI_ASSISTANT.ENABLED) {
        logger?.debug?.(
            `Assistant brain: AI_ASSISTANT_ENABLED is false; returning placeholder for channel ${context.channelId}`
        );
        return offlineReply();
    }

    // Fail closed: an absent audience is treated as internal, and only tools
    // declared for that audience are ever shown to the model.
    const audience: AssistantReplyAudience = context.audience ?? "internal";

    // The public visitor chat runs on the lighter model: high volume, and its
    // questions are lookup-and-summarise rather than deep reasoning. Internal
    // chats keep the stronger default.
    const model = audience === "public"
        ? (AI_ASSISTANT.PROVIDER === "anthropic"
            ? (ANTHROPIC.MODEL_LIGHT || ANTHROPIC.MODEL)
            : (AI_ASSISTANT.MODEL_LIGHT || AI_ASSISTANT.MODEL))
        : undefined;

    const ollamaTools = getAssistantTools(audience).map(toOllamaTool);
    const toolCtx: AssistantToolContext = {
        companyId: context.companyId,
        userId: context.userId,
        channelId: context.channelId,
        audience,
        languageCode: context.languageCode,
        logger
    };
    logger?.debug?.(
        `Assistant brain: ${ollamaTools.length} tool(s) offered for audience "${audience}"`
    );

    const historyMessages: OllamaChatMessage[] = (context.history ?? []).map(
        (turn): OllamaChatMessage => ({ role: turn.role, content: turn.content })
    );

    const messages: OllamaChatMessage[] = [
        { role: "system", content: buildSystemPrompt(context) },
        ...historyMessages,
        { role: "user", content: context.text }
    ];

    for (let iteration = 0; iteration < MAX_TOOL_ITERATIONS; iteration++) {
        const message = await assistantChat(messages, {
            tools: ollamaTools.length > 0 ? ollamaTools : undefined,
            logger,
            ...(model ? { model } : {})
        });

        const toolCalls = message.tool_calls ?? [];
        if (toolCalls.length === 0) {
            logger?.debug?.(`Assistant brain: reply generated for channel ${context.channelId}`);
            return message.content || EMPTY_REPLY_FALLBACK;
        }

        // Record the model's tool-request turn, then run each call and append its result.
        // `raw` carries the provider's own content blocks so they can be replayed
        // verbatim next turn — Claude rejects an assistant turn whose thinking
        // blocks were dropped. Ollama ignores it.
        messages.push({
            role: "assistant",
            content: message.content,
            tool_calls: toolCalls,
            ...(message.raw !== undefined ? { raw: message.raw } : {})
        });
        for (const call of toolCalls) {
            const resultText = await dispatchToolCall(call, toolCtx, logger);
            // `tool_call_id` pairs the result to its call for Claude; Ollama
            // pairs positionally and ignores it.
            messages.push({ role: "tool", content: resultText, tool_call_id: call.id });
        }
    }

    // Iteration budget exhausted — force a final text answer without tools.
    logger?.warn?.(
        `Assistant brain: tool-call budget (${MAX_TOOL_ITERATIONS}) exhausted for channel ${context.channelId}; forcing a text answer`
    );
    const finalMessage = await assistantChat(messages, { logger, ...(model ? { model } : {}) });
    return finalMessage.content || EMPTY_REPLY_FALLBACK;
}
